# My work env setup for Ubuntu
#

- hosts: all
  roles:
      - {role: common}
      - {role: tracing-tools}
      - {role: spf13}
      - {role: ngetchell.vscode, become: yes}
      - {role: vscode.plugins}
      - {role: spice.server, become: yes}
      - {role: my.intellij, become: yes}
