---
- stat: path={{intellij_install_dir}}
  register: intellij_install_dir_stat

- name: Install needed dependancies
  action: "{{ ansible_pkg_mgr }} state=present name={{ item }}"
  with_items:
    - tar
    - unzip
  tags: ["packages","intellij"]
  when: intellij_install_dir_stat.stat.exists == False

- name: Find latest version
  uri:
    url: "https://data.services.jetbrains.com/products/releases?code=IIU%2CIIC&latest=true&type=release"
    return_content: yes
    validate_certs: no
    body_format: json
  register: intellij_releases_response
  when: intellij_version == 'latest' and intellij_install_dir_stat.stat.exists == False
  tags: ["packages","intellij"]

- set_fact:
    intellij_version: "{{ intellij_releases_response.json.IIC.0.version }}"
  when: intellij_version == 'latest' and intellij_install_dir_stat.stat.exists == False
  tags: ["packages","intellij"]

- name: Download intellij
  get_url: url={{intellij_url}} dest={{intellij_tmp}}
  tags: ["packages","intellij"]
  when: intellij_install_dir_stat.stat.exists == False

- name: Ensure installation directory
  file:
    state=directory
    mode=0755
    dest={{intellij_install_dir}}
  tags: ["packages","intellij"]
  when: intellij_install_dir_stat.stat.exists == False

- name: Unarchive intellij
  unarchive:
    copy=no
    src={{intellij_tmp}}
    dest={{intellij_install_dir}}
  tags: ["packages","intellij"]
  when: intellij_install_dir_stat.stat.exists == False

#- name: Retreive intellij dir name
#  command: ls -t {{intellij_install_dir}}
#  register: result_intellij_folder_name
#  tags: ["configuration","intellij"]
#  when: intellij_install_dir_stat.stat.exists == False

#- name: Ensure intellij is configured
#  template: src=idea.properties.j2 dest={{intellij_install_dir}}/{{intellij_folder_name}}/bin/idea.properties
#  tags: ["configuration","intellij"]

#- name: Ensure intellij bin exist
#template: src=intellij.j2 dest=/usr/bin/intellij mode=755
#tags: ["configuration","intellij"]
#when: intellij_install_dir_stat.stat.exists == False

#- name: Ensure intellij shortcut is present
#  template: src=intellij.desktop.j2 dest=/usr/share/applications/intellij.desktop
#  tags: ["configuration","intellij"]
#  when: intellij_install_dir_stat.stat.exists == False
