---
# tasks file for common

- name: Ensure sudo group exists
  become: yes
  group:
    name: sudo
    state: present

- name: Ensure users in sudo group can sudo without password
  become: yes
  template:
    src: 95-sudo-group.j2
    dest: /etc/sudoers.d/95-sudo-group
    mode: 0440

- name: install essential packages
  become: yes
  apt:
    name: ['build-essential', 'make', 'curl', 'silversearcher-ag', 'dos2unix', 'default-jdk', 'git', 'vim', 'tmux', 'nginx', 'supervisor', 'golang', 'net-tools', 'sysstat', 'aptitude']
    state: present
    update_cache: yes

- name: configure git push.default
  command: git config --global push.default simple

- name: create HOME/gopath folder
  file:
      path: ~/gopath/
      state: directory
      mode: 0755

# sbt stuff from https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html
- name: Add sbt repo apt key by id from a keyserver
  become: yes
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823

- name: Add SBT Repo
  become: yes
  apt_repository:
      repo: 'deb http://dl.bintray.com/sbt/debian /'
      state: present

- name: Install sbt
  become: yes
  apt: 
      name: sbt
      state: present

